### ISSUE TITLE
Unable to load pocketbase using react

### ISSUE THREAD

**Issue by jasonabullard** [pocketbase/js-sdk#100]
I've been attempting to load the sdk in a fresh react-ts using vite but am constantly met with the following error:

Version: 0.8.2
Vite: 3.2.3

```
✘ [ERROR] Do not know how to load path: pocketbase

6:02:57 AM [vite] error while updating dependencies:
Error: Build failed with 1 error:
error: Do not know how to load path: pocketbase
    at failureErrorWithLog (/Users/jason/Development/Playground/pb-demo/node_modules/esbuild/lib/main.js:1575:15)
    at /Users/jason/Development/Playground/pb-demo/node_modules/esbuild/lib/main.js:1033:28
    at runOnEndCallbacks (/Users/jason/Development/Playground/pb-demo/node_modules/esbuild/lib/main.js:1447:61)
    at buildResponseToResult (/Users/jason/Development/Playground/pb-demo/node_modules/esbuild/lib/main.js:1031:7)
    at /Users/jason/Development/Playground/pb-demo/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/Users/jason/Development/Playground/pb-demo/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/Users/jason/Development/Playground/pb-demo/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/Users/jason/Development/Playground/pb-demo/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```

Here is how I am loading it:
```ts
import PocketBase from "pocketbase";

const client = new PocketBase(import.meta.env.PB_BACKEND_URL);

export default client;
```

and calling it:

```ts
import { Collection } from "pocketbase";
import { useEffect, useState } from "react";
import ApiClient from "./utils/ApiClient";

export default function App() {
  const [collections, setCollections] = useState<Collection[]>([]);

  useEffect(() => {
    ApiClient.collections.getList().then((colList) => {
      setCollections(colList.items);
    });
  }, []);

  return (
    <>
      <ul>
        {collections.map((collection) => (
          <li>{collection.title}</li>
        ))}
      </ul>
    </>
  );
}
```

**Comment by ganigeorgiev** [comment]
@jasonabullard I think this is the same as in https://github.com/pocketbase/js-sdk/issues/89 and https://github.com/pocketbase/js-sdk/issues/79#issuecomment-1321693737.

In short, if you have the executable in your frontend project, depending how your bundler is configured it is possible that on `import PocketBase from "pocketbase"` it will try to load the binary instead of the node module. Try renaming the executable to pocketbase_bin or move it to a different directory.

**Comment by diegoDeMiguelDPA** [comment]
Same issue here: Changing the executable to pocketbase_bin worked like a charm. Thanks @ganigeorgiev
