### ISSUE TITLE
Unable to subscribe to events while working in Node.js

### ISSUE THREAD

**Issue by sam-cutter** [pocketbase/js-sdk#154]
I've been playing around with Node.js, and I've noticed that I'm unable to subscribe to events. I get the following error when I do so: 

```
ReferenceError: EventSource is not defined
    at RealtimeService.initConnect (file:///C:/Users/Sam/Documents/Coding/clippy/backend/node_modules/pocketbase/dist/pocketbase.es.mjs:1:35616)
    at file:///C:/Users/Sam/Documents/Coding/clippy/backend/node_modules/pocketbase/dist/pocketbase.es.mjs:1:35312
    at new Promise (<anonymous>)
    at RealtimeService.<anonymous> (file:///C:/Users/Sam/Documents/Coding/clippy/backend/node_modules/pocketbase/dist/pocketbase.es.mjs:1:35210)
    at step (file:///C:/Users/Sam/Documents/Coding/clippy/backend/node_modules/pocketbase/dist/pocketbase.es.mjs:1:2088)
    at Object.next (file:///C:/Users/Sam/Documents/Coding/clippy/backend/node_modules/pocketbase/dist/pocketbase.es.mjs:1:2193)
    at file:///C:/Users/Sam/Documents/Coding/clippy/backend/node_modules/pocketbase/dist/pocketbase.es.mjs:1:1103
    at new Promise (<anonymous>)
    at __awaiter (file:///C:/Users/Sam/Documents/Coding/clippy/backend/node_modules/pocketbase/dist/pocketbase.es.mjs:1:789)
    at RealtimeService.connect (file:///C:/Users/Sam/Documents/Coding/clippy/backend/node_modules/pocketbase/dist/pocketbase.es.mjs:1:35082)
```

The section of my code where I attempt to subscribe to an event is as follows:
```
pb.collection("clips").subscribe("*", (e) => {
  console.log(e.record);
});
```

I am running Node.js 18.14.2, with PocketBase 0.11.1.

Also, in case it makes a difference, I had to set ` "type": "module"` in my package.json file in order to `import` PocketBase.

It would be really helpful to be able to subscribe to events. Is there another way I can do this? Thanks.

**Comment by ganigeorgiev** [comment]
You'll have to load an `EventSource` polyfill for Node, eg.:

```js
// npm install eventsource --save
import eventsource from 'eventsource';

global.EventSource = eventsource;
```

> Also, in case it makes a difference, I had to set  "type": "module" in my package.json file in order to import PocketBase.

Yes, this is required because the JS SDK is ESM bundled by default. For CommonJS import style you have to use the cjs bundle, but I don't recommend it.

This and other node caveats could be found in https://github.com/pocketbase/js-sdk#nodejs-via-npm

**Comment by sam-cutter** [comment]
Thank you.
