### ISSUE TITLE
Cant setup with express when generated with NX's @nrwl/express

### ISSUE THREAD

**Issue by moonryc** [pocketbase/js-sdk#72]
```
nx run backend:serve

chunk (runtime: main) main.js (main) 1.26 KiB [entry] [rendered]
webpack compiled successfully (31d8753af3173895)
Debugger listening on ws://localhost:9229/112d0caf-01be-4704-918c-bd95e89a8226
Debugger listening on ws://localhost:9229/112d0caf-01be-4704-918c-bd95e89a8226
For help, see: https://nodejs.org/en/docs/inspector
Listening at http://localhost:3333/api

/Users/ryanmoon/Desktop/Repos/learning/cloud-drive-clone/node_modules/@nrwl/js/src/executors/node/node-with-require-overrides.js:16
        return originalLoader.apply(this, arguments);
                              ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/ryanmoon/Desktop/Repos/learning/cloud-drive-clone/node_modules/pocketbase/dist/pocketbase.es.mjs not supported.
Instead change the require of /Users/ryanmoon/Desktop/Repos/learning/cloud-drive-clone/node_modules/pocketbase/dist/pocketbase.es.mjs to a dynamic import() which is available in all CommonJS modules.
    at Function.Module._load (/Users/ryanmoon/Desktop/Repos/learning/cloud-drive-clone/node_modules/@nrwl/js/src/executors/node/node-with-require-overrides.js:16:31)
    at Object.pocketbase (/Users/ryanmoon/Desktop/Repos/learning/cloud-drive-clone/dist/apps/backend/main.js:29:18)
    at __webpack_require__ (/Users/ryanmoon/Desktop/Repos/learning/cloud-drive-clone/dist/apps/backend/main.js:67:41)
    at /Users/ryanmoon/Desktop/Repos/learning/cloud-drive-clone/dist/apps/backend/main.js:92:72
Type-checking in progress...
No errors found.
```

Steps to replicate:
1) create a nx workspace with `npx create-nx-workspace`
2) generate a express app with @nrwl/express
3) added pocketbase to root dir
4) `yarn add pocketbase`
5) set up pocketbase as below

```ts
/**
 * This is not a production server yet!
 * This is only a minimal backend to get started.
 */

import * as express from 'express';
import * as path from 'path';

require('cross-fetch/polyfill');
global.EventSource = require('eventsource')
import PocketBase from 'pocketbase'
// const PocketBase = require('pocketbase/cjs')

const client = new PocketBase("http://127.0.0.1:8090")


const app = express();

app.use('/assets', express.static(path.join(__dirname, 'assets')));

app.get('/api', (req, res) => {
  res.send({ message: 'Welcome to backend!' });
});

const port = process.env.port || 3333;
const server = app.listen(port, () => {
  console.log(`Listening at http://localhost:${port}/api`);
});
server.on('error', console.error);

```

**Comment by ganigeorgiev** [comment]
I don't think this is related only to the SDK and from the error message it seems that `@nrwl/express` for some reason doesn't work with esm modules.

There are several open issues in the upstream library similar to this one in https://github.com/nrwl/nx/search?q=es+module&type=issues.

There is even a PR that is expected to fix it but currently it is closed - https://github.com/nrwl/nx/pull/10414 with the following resolution in comment https://github.com/nrwl/nx/pull/10414#issuecomment-1255972138:

> Closing because we'd like to implement a better fix across Nx to support ESM instead of dynamic import hack. Thank you bulldog98 for the PR but I'll be closing this.

Unfortunately I'm not familiar with `Nx` ecosystem and I don't know how that works, but you can look for other similar issues or ask in the Nx support channel for workarounds.
