### ISSUE TITLE
TypeError: this.baseUrl.endsWith is not a function

### ISSUE THREAD

**Issue by Xyndra** [pocketbase/js-sdk#84]
`TypeError: this.baseUrl.endsWith is not a function`

I am trying to create a user with a form using this code
Svelte:
```svelte
<div class="flex flex-col items-center h-full w-full">
    <h2 class="mt-2 text-center text-3xl font-bold tracking-tight text-base-content">
        Register for an account
    </h2>
    <p class="text-center mt-1">
        <!-- svelte-ignore a11y-missing-content -->
        Or <a href="/login" class="text-primary font-medium hover:cursor-pointer hover:underline">sign in</a>
        if you already have an account
    </p>
    <form action="?/register" method="POST" class="flex flex-col items-center space-y-2 w-full pt-4">
		<div class="form-control w-full max-w-md">
			<label for="name" class="label font-medium pb-1">
				<span class="label-text">Name</span>
			</label>
			<input type="text" name="name" class="input input-bordered w-full max-w-md" />
		</div>
		<div class="form-control w-full max-w-md">
			<label for="email" class="label font-medium pb-1">
				<span class="label-text">Email</span>
			</label>
			<input type="email" name="email" class="input input-bordered w-full max-w-md" />
		</div>
		<div class="form-control w-full max-w-md">
			<label for="password" class="label font-medium pb-1">
				<span class="label-text">Password</span>
			</label>
			<input type="password" name="password" class="input input-bordered w-full max-w-md" />
		</div>
		<div class="form-control w-full max-w-md">
			<label for="passwordConfirm" class="label font-medium pb-1">
				<span class="label-text">Confirm Password</span>
			</label>
			<input type="password" name="passwordConfirm" class="input input-bordered w-full max-w-md" />
		</div>
		<div class="w-full max-w-md pt-2">
			<button type="submit" class="btn btn-primary w-full">Register</button>
		</div>
	</form>
</div>
```
And JS:
```javascript
import { error, redirect } from "@sveltejs/kit"
import { generateUsername } from "../../lib/utils"

export const actions = {
    register: async ({locals, request}) => {
        const body = Object.fromEntries(await request.formData())

        let username = generateUsername(body.name.split(' ').join('')).toLowerCase()

        try {
            await locals.pb.collection('users').create({
                username,
                ...body
            })
            await locals.pb.collection('users').requestVerification(body.email)
        } catch (e) {
            console.log(e)
            throw error(500, 'Something went wrong');
        }

        throw redirect('/login')
    }
}
```

Full error:
```
TypeError: this.baseUrl.endsWith is not a function
    at t.buildUrl (file:///C:/Users/<User>/WebstormProjects/DeveloperBountyBoard/node_modules/pocketbase/dist/pocketbase.es.mjs:1:34294)
    at t.<anonymous> (file:///C:/Users/<User>/WebstormProjects/DeveloperBountyBoard/node_modules/pocketbase/dist/pocketbase.es.mjs:1:33267)
    at file:///C:/Users/<User>/WebstormProjects/DeveloperBountyBoard/node_modules/pocketbase/dist/pocketbase.es.mjs:1:1905
    at Object.next (file:///C:/Users/<User>/WebstormProjects/DeveloperBountyBoard/node_modules/pocketbase/dist/pocketbase.es.mjs:1:2010)
    at file:///C:/Users/<User>/WebstormProjects/DeveloperBountyBoard/node_modules/pocketbase/dist/pocketbase.es.mjs:1:947
    at new Promise (<anonymous>)
    at i (file:///C:/Users/<User>/WebstormProjects/DeveloperBountyBoard/node_modules/pocketbase/dist/pocketbase.es.mjs:1:692)
    at t.send (file:///C:/Users/<User>/WebstormProjects/DeveloperBountyBoard/node_modules/pocketbase/dist/pocketbase.es.mjs:1:32133)
    at n._create (file:///C:/Users/<User>/WebstormProjects/DeveloperBountyBoard/node_modules/pocketbase/dist/pocketbase.es.mjs:1:13782)
    at n.create (file:///C:/Users/<User>/WebstormProjects/DeveloperBountyBoard/node_modules/pocketbase/dist/pocketbase.es.mjs:1:11968)
```

**Comment by ganigeorgiev** [comment]
I'm not able to reproduce the error.

What version of the SDK you are using?

Could you provide a code sample how you are instantiating the PocketBase instance?

**Comment by Xyndra** [comment]
[src.zip](https://github.com/pocketbase/js-sdk/files/10086938/src.zip)
This is the zip of the src, I'm running `pocketbase_0.8.0_windows_amd64` version
This is the package.json:
```json
{
	"name": "developerbountyboard",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"dev": "vite dev",
		"build": "vite build",
		"preview": "vite preview",
		"test": "playwright test",
		"lint": "prettier --plugin-search-dir . --check . && eslint .",
		"format": "prettier --plugin-search-dir . --write ."
	},
	"devDependencies": {
		"@playwright/test": "1.25.0",
		"@sveltejs/adapter-auto": "next",
		"@sveltejs/kit": "next",
		"autoprefixer": "^10.4.7",
		"daisyui": "^2.42.1",
		"eslint": "^8.16.0",
		"eslint-config-prettier": "^8.3.0",
		"eslint-plugin-svelte3": "^4.0.0",
		"postcss": "^8.4.14",
		"postcss-load-config": "^4.0.1",
		"prettier": "^2.6.2",
		"prettier-plugin-svelte": "^2.7.0",
		"svelte": "^3.44.0",
		"svelte-preprocess": "^4.10.7",
		"tailwindcss": "^3.1.5",
		"vite": "^3.1.0"
	},
	"type": "module",
	"dependencies": {
		"pocketbase": "^0.8.0"
	}
}
```

**Comment by ganigeorgiev** [comment]
I don't have currently a virtual machine to open safely the above file. Could you provide just a code snippet of how you are creating the PocketBase instance, or better - create a minimal reprodicable repo and link it here?

**Comment by ganigeorgiev** [comment]
@Xyndra My guess is that you are not passing a string to the `new PocketBase(url)` constructor.
If you are using env variables make sure that they are defined for the environment where your code is executed (browser and/or node; you can add a `console.log("url:", url)` before the instantiation to confirm it).

**Comment by Xyndra** [comment]
[Uploading debug.zip…]()
I finished creating an somewhat minimal version of the repo which also throws the error

My Connection script does this:
```js
import PocketBase from 'pocketbase'
import { serializeNonPOJOs } from './lib/utils'

export const handle = async ({event, resolve}) => {
    event.locals.pb = new PocketBase({url: 'http://127.0.0.1:8090'})
    event.locals.pb.authStore.loadFromCookie(event.request.headers.cookie || '')

    if (event.locals.pb.authStore.isValid) {
        event.locals.user = serializeNonPOJOs(event.locals.pb.authStore.model)
    } else {
        event.locals.user = undefined
    }

    const response = await resolve(event)

    response.headers.set('set-cookie', event.locals.pb.authStore.exportToCookie({secure:false}))

    return response
}
```

**Comment by ganigeorgiev** [comment]
@Xyndra The url needs to be passed as string, you cannot be defined as an object prop, or in other words:

```js
event.locals.pb = new PocketBase('http://127.0.0.1:8090')
```

**Comment by Xyndra** [comment]
Oops, sorry
