### ISSUE TITLE
TypeError: XMLHttpRequest is not a constructor 

### ISSUE THREAD

**Issue by TIM88-DOT** [pocketbase/js-sdk#86]
I have this issue related to eventsource apparently 🤔  (i'm using node 16 btw)

**Imports :**
```
import PocketBase from 'pocketbase';
import { NativeEventSource, EventSourcePolyfill } from 'event-source-polyfill';
import 'cross-fetch/dist/node-polyfill.js';

const EventSource = NativeEventSource || EventSourcePolyfill;
// OR: may also need to set as global property
global.EventSource = NativeEventSource || EventSourcePolyfill;
```
**Code that's causing the error :**
```
pb.collection('subscribers').subscribe('*', function (e) {
    console.log(e.record);
});
```
**Error i'm getting :** 
```
C:\Users\G\Desktop\w0wbot\wow-subscription-bot\node_modules\event-source-polyfill\src\eventsource.js:730
        ? new XMLHttpRequest()
          ^

TypeError: XMLHttpRequest is not a constructor
    at getBestXHRTransport (C:\Users\G\Desktop\w0wbot\wow-subscription-bot\node_modules\event-source-polyfill\src\eventsource.js:730:11)
    at start (C:\Users\G\Desktop\w0wbot\wow-subscription-bot\node_modules\event-source-polyfill\src\eventsource.js:750:148)
    at new EventSourcePolyfill (C:\Users\G\Desktop\w0wbot\wow-subscription-bot\node_modules\event-source-polyfill\src\eventsource.js:725:5)      
    at n.connect (file:///C:/Users/G/Desktop/w0wbot/wow-subscription-bot/node_modules/pocketbase/dist/pocketbase.es.mjs:1:30774)
    at n.<anonymous> (file:///C:/Users/G/Desktop/w0wbot/wow-subscription-bot/node_modules/pocketbase/dist/pocketbase.es.mjs:1:27021)
    at file:///C:/Users/G/Desktop/w0wbot/wow-subscription-bot/node_modules/pocketbase/dist/pocketbase.es.mjs:1:1905
    at Object.next (file:///C:/Users/G/Desktop/w0wbot/wow-subscription-bot/node_modules/pocketbase/dist/pocketbase.es.mjs:1:2010)
    at file:///C:/Users/G/Desktop/w0wbot/wow-subscription-bot/node_modules/pocketbase/dist/pocketbase.es.mjs:1:947
    at new Promise (<anonymous>)
    at i (file:///C:/Users/G/Desktop/w0wbot/wow-subscription-bot/node_modules/pocketbase/dist/pocketbase.es.mjs:1:692)
    at n.subscribe (file:///C:/Users/G/Desktop/w0wbot/wow-subscription-bot/node_modules/pocketbase/dist/pocketbase.es.mjs:1:26681)
    at n.<anonymous> (file:///C:/Users/G/Desktop/w0wbot/wow-subscription-bot/node_modules/pocketbase/dist/pocketbase.es.mjs:1:18203)
    at file:///C:/Users/G/Desktop/w0wbot/wow-subscription-bot/node_modules/pocketbase/dist/pocketbase.es.mjs:1:1905
    at Object.next (file:///C:/Users/G/Desktop/w0wbot/wow-subscription-bot/node_modules/pocketbase/dist/pocketbase.es.mjs:1:2010)
    at file:///C:/Users/G/Desktop/w0wbot/wow-subscription-bot/node_modules/pocketbase/dist/pocketbase.es.mjs:1:947
    at new Promise (<anonymous>)
    at i (file:///C:/Users/G/Desktop/w0wbot/wow-subscription-bot/node_modules/pocketbase/dist/pocketbase.es.mjs:1:692)
    at n.subscribe (file:///C:/Users/G/Desktop/w0wbot/wow-subscription-bot/node_modules/pocketbase/dist/pocketbase.es.mjs:1:17756)
    at file:///C:/Users/G/Desktop/w0wbot/wow-subscription-bot/index.js:147:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by ganigeorgiev** [comment]
I don't recommend using the `event-source-polyfill` package (see https://github.com/Yaffle/EventSource/issues/202).

Instead, for EventSource polyfill I recommend https://github.com/EventSource/eventsource:

```js
// npm install eventsource --save
global.EventSource = require('eventsource');
```

---

For the fetch polyfill - for better cross platform support I recommend https://github.com/lquixada/cross-fetch (internally it uses node-fetch):

```js
// npm install cross-fetch --save
require('cross-fetch/polyfill');
```

---

You can find more information and other caveats in the Installation section of the README - https://github.com/pocketbase/js-sdk#installation
