### ISSUE TITLE
vite can't load pocketbase when running `npm run dev`

### ISSUE THREAD

**Issue by alexdoffgit** [pocketbase/js-sdk#89]
i was trying to load data from collection, this is the code

```javascript
import PocketBase from 'pocketbase'

(async () => {
  const pb = new PocketBase('http://127.0.0.1:8090')
  
  const records = await pb.collection('todos').getFullList(200, {
    sort: '-created',
  });
  
  console.log(records)
})()
```

then i try to run vite dev server with `npm run dev`, and it give this error

```
6:44:29 PM [vite] error while updating dependencies:
Error: Build failed with 1 error:
error: Do not know how to load path: pocketbase
    at failureErrorWithLog (/arfchive/scratchpad/pocketbase-js-sdk-try/node_modules/esbuild/lib/main.js:1574:15)
    at /arfchive/scratchpad/pocketbase-js-sdk-try/node_modules/esbuild/lib/main.js:1032:28
    at runOnEndCallbacks (/arfchive/scratchpad/pocketbase-js-sdk-try/node_modules/esbuild/lib/main.js:1446:61)
    at buildResponseToResult (/arfchive/scratchpad/pocketbase-js-sdk-try/node_modules/esbuild/lib/main.js:1030:7)
    at /arfchive/scratchpad/pocketbase-js-sdk-try/node_modules/esbuild/lib/main.js:1142:14
    at responseCallbacks.<computed> (/arfchive/scratchpad/pocketbase-js-sdk-try/node_modules/esbuild/lib/main.js:679:9)
    at handleIncomingPacket (/arfchive/scratchpad/pocketbase-js-sdk-try/node_modules/esbuild/lib/main.js:734:9)
    at Socket.readFromStdout (/arfchive/scratchpad/pocketbase-js-sdk-try/node_modules/esbuild/lib/main.js:655:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
```

it work though when i try to build it with `npm run build`

i use `npm create vite@latest --template javascript` for the project

version:
- pocketbase v0.8.0
- pocketbase sdk v0.8.1

for me the current workaround is to import pocketbase path directly in the node module
```javascript
import PocketBase from './node_modules/pocketbase/dist/pocketbase.es.mjs'
```

**Comment by ganigeorgiev** [comment]
I think this is similar to https://github.com/pocketbase/js-sdk/issues/79.

If you have the executable in your frontend project, depending how vite is configured it is possible that on `import PocketBase from "pocketbase"` vite will try to load the binary instead of the node module. Try renaming the executable to `pocketbase_bin` or move it to a different directory.
